name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.6"
          cache: true

      - name: Go mod tidy
        working-directory: e-commerce-api
        run: go mod tidy

      - name: Download dependencies
        working-directory: e-commerce-api
        run: go mod download

      - name: Run tests
        working-directory: e-commerce-api
        run: go test ./...

      - name: Build application
        working-directory: e-commerce-api
        run: go build ./...
